name: NRMS Sync

on:
  schedule:
    # Суббота в 06:00 по МСК (03:00 UTC)
    - cron: '0 3 * * 6'
  workflow_dispatch: 

jobs:
  sync_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install pandas requests
      - name: Run Sync
        env:
          NRMS_USERNAME: ${{ secrets.NRMS_USERNAME }}
          NRMS_PASSWORD: ${{ secrets.NRMS_PASSWORD }}
          SHEET_CSV_URL: ${{ secrets.SHEET_CSV_URL }}
        run: python worker.py
