name: Daily Bot (Weather & Birthdays)

on:
  schedule:
    # Запуск каждый день в 05:00 UTC (08:00 по МСК)
    - cron: '0 5 * * *'
  workflow_dispatch: # Чтобы можно было запустить вручную кнопкой

jobs:
  send_report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install requests
      - name: Run bot
        env:
          VK_TOKEN: ${{ secrets.VK_TOKEN }}
          VK_CHAT_IDS: ${{ secrets.VK_CHAT_IDS }}
          VK_GROUP_ID: ${{ secrets.VK_GROUP_ID }}
        run: python bot.py
